# Generated by Django 5.0.4 on 2024-04-25 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=20)),
                ('album_image', models.FileField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('song', models.FileField(upload_to='song')),
                ('picture', models.FileField(upload_to='picture')),
                ('singer', models.CharField(max_length=20)),
                ('album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music_player.album')),
            ],
        ),
    ]
